# -*- coding: utf-8 -*-
"""Sri_Lankan_Food_Trainer_Tutorial_Enhanced.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17QB6M18sc0AvvNTnqRGjOqVC3xQITuYi

```
╔══════════════════════════════════════════════════════════════════════╗
║                                                                      ║
║           🍽️ SRI LANKAN FOOD RECOGNITION MODEL TRAINER 🍽️           ║
║                                                                      ║
║          Extend the model with your own food classes!               ║
║                                                                      ║
╚══════════════════════════════════════════════════════════════════════╝
```

# 📚 Tutorial Overview

Welcome! This notebook will teach you how to **extend** the Sri Lankan Food Recognition model with your own food classes using just **3 lines of code**!

## 🎯 What You'll Learn

- ✅ How to use the `srilankan-food-trainer` library
- ✅ How to add your own vegetable/food classes
- ✅ How to train the model with minimal code
- ✅ How to download and use your extended model

## 📋 What You Need

1. **Images of your food class** (30-50 images recommended)
   - Format: JPG, PNG, or JPEG
   - Quality: Clear, well-lit photos
   - Variety: Different angles and presentations

2. **A folder structure** like this:
   ```
   potato_tempered/
   ├── image1.jpg
   ├── image2.jpg
   ├── image3.jpg
   └── ...
   ```

3. **Zip the folder** before uploading

## ⏱️ Time Required

- Setup: **2 minutes**
- Training: **30-60 minutes** (depending on number of images)
- Total: **~1 hour**

## 🚀 Let's Get Started!

Run the cells below **in order** from top to bottom.

---

# 🎬 Quick Demo: See What's Possible!

Before we start, let's see what this library can do:
"""

"""
╔══════════════════════════════════════════════════════════════════════╗
║                          WELCOME! 👋                                 ║
╚══════════════════════════════════════════════════════════════════════╝

This tutorial shows you how to extend a pre-trained AI model
to recognize NEW types of Sri Lankan food!

💡 Key Concept: TRANSFER LEARNING
   Instead of training from scratch (which takes days),
   we'll use a pre-trained model and teach it ONE new class.
   This takes only 30-60 minutes!

🎯 What happens:
   ➡️  Original model: Recognizes 8 classes
   ➡️  You add: 1 new class (e.g., potato_tempered)
   ➡️  Result: Model recognizes 9 classes (8 old + 1 new)

✨ The best part?
   The model STILL recognizes the original 8 classes!
   It doesn't forget them - it just learns something new!
"""

print("="*70)
print("🎉 WELCOME TO SRI LANKAN FOOD TRAINER!")
print("="*70)

print("\n📚 In this tutorial, you'll:")
print("   1️⃣  Install the library (30 seconds)")
print("   2️⃣  Upload your food images (1 minute)")
print("   3️⃣  Train the model (30-60 minutes)")
print("   4️⃣  Download your extended model (30 seconds)")

print("\n💡 Pro Tip:")
print("   For best results, use 30-50 clear, well-lit images")
print("   of your food from different angles.")

print("\n🚀 Let's get started!\n")

"""---

# 📦 Step 1: Install the Library

First, we'll install the `srilankan-food-trainer` library. This library contains all the code needed to extend the model.

⏱️ **Time:** ~30 seconds

▶️ **Run the cell below:**
"""

# ============================================================================
# STEP 1: INSTALL THE LIBRARY
# ============================================================================

"""
What's happening here?
----------------------
We're installing the 'srilankan-food-trainer' library from PyPI.
This is a custom Python package that simplifies model extension.

The '-q' flag means 'quiet mode' - it won't show all the installation details.

This installs:
  ✅ PyTorch (deep learning framework)
  ✅ torchvision (computer vision tools)
  ✅ huggingface_hub (to download pre-trained model)
  ✅ Helper utilities for training
"""

print("📦 Installing srilankan-food-trainer library...")
print("   This may take 20-30 seconds...\n")

!pip install -q srilankan-food-trainer

print("✅ Library installed successfully!")
print("\n💡 What we installed:")
print("   - FoodModelExtender: Main class for extending the model")
print("   - Pre-trained model downloader")
print("   - Training utilities")
print("\n➡️  Ready for Step 2!")

"""---

# 🔧 Step 2: Initialize the Model Extender

Now we'll create a `FoodModelExtender` object. This object will:
- Download the pre-trained model (if not already cached)
- Set up the training environment
- Prepare to accept your new food class

⏱️ **Time:** ~10 seconds

▶️ **Run the cell below:**
"""

# ============================================================================
# STEP 2: CREATE THE MODEL EXTENDER
# ============================================================================

"""
What's happening here?
----------------------
We're importing the FoodModelExtender class and creating an instance.

Parameters:
  - verbose=True: Shows detailed progress messages (helpful for learning!)

Behind the scenes, this:
  1. Checks if you have GPU (for faster training)
  2. Sets up the model architecture
  3. Prepares to download the pre-trained model when needed

The pre-trained model contains:
  ✅ 8 vegetable classes across cooking states
  ✅ Learned features from 2000+ training images
  ✅ 90%+ accuracy on validation data
"""

from srilankan_food_trainer import FoodModelExtender

print("="*70)
print("🔧 INITIALIZING FOOD MODEL EXTENDER")
print("="*70)

print("\n📝 Creating extender object...")
print("   This sets up the training environment\n")

# Create the extender with verbose output
extender = FoodModelExtender(verbose=True)

print("\n✅ Extender initialized successfully!")
print("\n📊 Current status:")
print("   - Pre-trained model: Ready to download")
print("   - Original classes: 8 (will be preserved)")
print("   - New classes: 0 (you'll add yours next!)")
print("\n➡️  Ready for Step 3!")

"""---

# 📤 Step 3: Upload Your Food Images

Time to add YOUR food class! You'll upload a ZIP file containing your images.

## 📋 Preparation Checklist

Before running this cell, make sure you have:

- ✅ **30-50 images** of your food (more is better!)
- ✅ **Clear, well-lit photos** (avoid blurry images)
- ✅ **Different angles** (top view, side view, close-up)
- ✅ **Consistent subject** (all images should be the same food type)
- ✅ **Organized in a folder** (e.g., `potato_tempered/`)
- ✅ **Zipped the folder** (e.g., `potato_tempered.zip`)

## 📁 Folder Structure Example

```
potato_tempered.zip
└── potato_tempered/          ← Folder name = class name
    ├── img_001.jpg
    ├── img_002.jpg
    ├── img_003.jpg
    └── ... (30-50 images total)
```

⏱️ **Time:** ~1-2 minutes (depending on file size)

▶️ **Run the cell below and upload your ZIP file:**
"""

# ============================================================================
# STEP 3: UPLOAD YOUR IMAGES
# ============================================================================

"""
What's happening here?
----------------------
We're using Google Colab's file upload feature to get your images.

Important naming convention:
  - ZIP filename = class name
  - Example: 'potato_tempered.zip' → class name is 'potato_tempered'
  - Use underscores (_) not spaces
  - Use lowercase for consistency

What happens after upload:
  1. File is uploaded to Colab's temporary storage
  2. We extract the class name from the filename
  3. Ready to add to the model!

💡 Pro Tips:
  - If upload is slow, check your internet connection
  - If upload fails, try a smaller ZIP file
  - Maximum recommended: 100 images per class
"""

from google.colab import files
import os

print("="*70)
print("📤 UPLOAD YOUR FOOD IMAGES")
print("="*70)

print("\n📋 Before uploading, make sure:")
print("   ✅ Images are clear and well-lit")
print("   ✅ All images are of the SAME food type")
print("   ✅ You have 30-50 images (minimum 20)")
print("   ✅ Images are inside a folder")
print("   ✅ Folder is zipped")

print("\n🎯 Naming your file:")
print("   - Good: potato_tempered.zip")
print("   - Good: eggplant_curry.zip")
print("   - Bad: My Food.zip (has space)")
print("   - Bad: images.zip (not descriptive)")

print("\n⏳ Click 'Choose Files' below and select your ZIP file...\n")

# Upload file
uploaded = files.upload()

# Process uploaded file
if uploaded:
    filename = list(uploaded.keys())[0]
    file_size_mb = os.path.getsize(filename) / (1024 * 1024)

    print("\n" + "="*70)
    print("✅ FILE UPLOADED SUCCESSFULLY!")
    print("="*70)

    print(f"\n📦 File details:")
    print(f"   - Filename: {filename}")
    print(f"   - Size: {file_size_mb:.2f} MB")

    # Extract class name from filename
    class_name = filename.replace('.zip', '').replace('.ZIP', '')
    print(f"   - Detected class name: '{class_name}'")

    print("\n💾 File saved to: /content/{}".format(filename))
    print("\n➡️  Ready for Step 4!")

else:
    print("\n❌ ERROR: No file uploaded!")
    print("\n💡 Please try again:")
    print("   1. Run this cell again")
    print("   2. Click 'Choose Files'")
    print("   3. Select your ZIP file")
    raise Exception("Please upload your data file to continue")

"""---

# 📸 Step 4: Add Your Class to the Model

Now we'll add your food class to the model. This process will:
1. **Extract** your ZIP file
2. **Validate** your images (check format, count, etc.)
3. **Split** data into training (70%), validation (15%), and test (15%) sets
4. **Prepare** for training

⏱️ **Time:** ~10 seconds

▶️ **Run the cell below:**
"""

# ============================================================================
# STEP 4: ADD YOUR CLASS TO THE MODEL
# ============================================================================

"""
What's happening here?
----------------------
The add_class() method does several important things:

1. EXTRACTION:
   - Unzips your file
   - Finds the folder containing images

2. VALIDATION:
   - Counts images (needs minimum 20, recommends 30-50)
   - Checks image formats (JPG, PNG, JPEG)
   - Verifies images can be opened

3. DATA SPLITTING:
   - 70% for training (model learns from these)
   - 15% for validation (checks progress during training)
   - 15% for testing (final evaluation)

4. PREPARATION:
   - Organizes files in proper structure
   - Creates labels
   - Sets up data loaders

Parameters explained:
  - class_name: Name of your food class (from ZIP filename)
  - images_path: Path to your ZIP file
  - auto_extract: Automatically unzip the file (True/False)
"""

print("="*70)
print("📸 ADDING YOUR CLASS TO THE MODEL")
print("="*70)

print(f"\n🎯 Processing class: '{class_name}'")
print("\n⏳ This will:")
print("   1. Extract your ZIP file")
print("   2. Count and validate images")
print("   3. Split into train/validation/test sets")
print("   4. Prepare for training\n")

# Get the file path
zip_path = f'/content/{filename}'

# Add class to the model
success = extender.add_class(
    class_name=class_name,
    images_path=zip_path,
    auto_extract=True  # Automatically unzip
)

print("\n" + "="*70)

if success:
    print("✅ CLASS ADDED SUCCESSFULLY!")
    print("="*70)

    print(f"\n📊 Summary:")
    print(f"   - Class name: {class_name}")
    print(f"   - Original model classes: 8")
    print(f"   - Your new class: 1")
    print(f"   - Total classes after training: 9")

    print("\n💡 Important:")
    print("   The model will learn to recognize your new class")
    print("   WITHOUT forgetting the original 8 classes!")

    print("\n➡️  Ready for Step 5 (Training)!")

else:
    print("❌ FAILED TO ADD CLASS")
    print("="*70)
    print("\n💡 Possible issues:")
    print("   - Not enough images (need minimum 20)")
    print("   - Images in wrong format (use JPG/PNG)")
    print("   - ZIP structure is incorrect")
    print("\n📋 Check the error message above for details")
    raise Exception("Class addition failed. Please fix the issues and try again.")

"""---

# 🏋️ Step 5: Train the Model

This is where the magic happens! The model will learn to recognize your new food class.

## 🧠 What is Training?

Training is the process where the AI model:
1. **Looks** at your images
2. **Tries** to recognize patterns
3. **Makes** mistakes (initially)
4. **Learns** from those mistakes
5. **Improves** its accuracy over time

Think of it like teaching a child to recognize different foods - it takes examples and practice!

## 📊 Training Process

```
Epoch 1/50:  Model sees all training images once → Accuracy: 65%
Epoch 2/50:  Model sees all training images again → Accuracy: 72%
Epoch 3/50:  Model sees all training images again → Accuracy: 78%
...
Epoch 50/50: Final round → Accuracy: 90%
```

## ⏱️ Expected Time

- With GPU: **30-45 minutes** ⚡ (faster)
- With CPU: **60-90 minutes** 🐌 (slower)

Colab usually provides a free GPU, so it should be faster!

## 📈 What You'll See

During training, you'll see:
- **Progress bar**: Shows which epoch we're on
- **Training loss**: Lower is better (model's mistakes)
- **Validation accuracy**: Higher is better (model's correctness)
- **Time per epoch**: How long each round takes

## ☕ Pro Tip

This is a good time to:
- Read about transfer learning 📚
- Watch the progress occasionally 👀

▶️ **Run the cell below to start training:**
"""

# ============================================================================
# STEP 5: TRAIN THE MODEL
# ============================================================================

"""
What's happening here?
----------------------
This is the core of the tutorial - training the model!

The training process:

1. INITIALIZATION (first time only):
   - Downloads pre-trained model from Hugging Face
   - Loads the 8 original classes
   - Sets up the neural network

2. FINE-TUNING (each epoch):
   - Shows model your training images
   - Model makes predictions
   - Calculates how wrong the predictions are (loss)
   - Adjusts model weights to improve
   - Tests on validation images

3. MONITORING:
   - Tracks best accuracy
   - Saves best model version
   - Prevents overfitting

Training Parameters:
  - epochs: Number of times to see all training data (default: 50)
  - learning_rate: How fast to learn (default: 0.00001, very small!)
  - batch_size: Images processed together (default: configured in library)

Why such a low learning rate?
  We're fine-tuning, not training from scratch!
  Small changes preserve the original 8 classes.

Output metrics explained:
  - Train Loss: Lower = better (0.1 is great, 1.0 is okay)
  - Val Accuracy: Higher = better (90%+ is excellent, 80%+ is good)
  - Time: Depends on GPU availability
"""

print("="*70)
print("🏋️ TRAINING THE MODEL")
print("="*70)

print("\n🎯 What will happen:")
print("   1. Download pre-trained model (first time only)")
print("   2. Load original 8 classes")
print("   3. Train for 50 epochs (~30-60 minutes)")
print("   4. Save best model automatically")

print("\n💡 Understanding the output:")
print("   - Epoch: One complete pass through all training images")
print("   - Loss: How wrong the model is (lower = better)")
print("   - Val Acc: Validation accuracy (higher = better)")
print("   - Target: 85-90% validation accuracy")

print("\n⏰ Estimated time:")
print("   - With GPU: 30-45 minutes ⚡")
print("   - With CPU: 60-90 minutes 🐌")

print("\n☕ This is a great time for a coffee break!")
print("   The notebook will continue running in the background.\n")

print("="*70)
print("🚀 STARTING TRAINING...")
print("="*70 + "\n")

# Train the model
# This will take 30-60 minutes depending on GPU availability
results = extender.train(
    epochs=50,              # Number of training rounds
    save_checkpoints=True   # Save best model automatically
)

# Training complete! Show results
print("\n" + "="*70)
print("🎉 TRAINING COMPLETE!")
print("="*70)

print("\n📊 Final Results:")
print(f"   ✅ Best Validation Accuracy: {results['best_val_acc']:.2f}%")
print(f"   ⏱️  Total Training Time: {results.get('total_time', 0)/60:.1f} minutes")
print(f"   💾 Model saved automatically")

print("\n🎯 Performance Guide:")
if results['best_val_acc'] >= 90:
    print("   🌟 EXCELLENT! (90%+) - Your model is performing great!")
elif results['best_val_acc'] >= 85:
    print("   ✅ VERY GOOD! (85-90%) - Model should work well in practice.")
elif results['best_val_acc'] >= 80:
    print("   👍 GOOD! (80-85%) - Decent performance, consider more training.")
else:
    print("   ⚠️  NEEDS IMPROVEMENT (<80%) - Consider:")
    print("      - Adding more images")
    print("      - Training for more epochs")
    print("      - Checking image quality")

print("\n💡 What your model can now do:")
print("   ✅ Recognize all 8 original classes (carrot, beans, pumpkin, etc.)")
print(f"   ✅ Recognize your new class: {class_name}")
print("   ✅ Total: 9 classes in one model!")

print("\n➡️  Ready for Step 6 (Save & Download)!")

"""---

# 💾 Step 6: Save and Download Your Model

Congratulations! Your model is trained. Now let's save it and download it to your computer.

## 📦 What Gets Saved

The saved file contains:
- ✅ **Model weights** (the learned parameters)
- ✅ **Original 8 classes** (preserved knowledge)
- ✅ **Your new class** (newly learned)
- ✅ **Training history** (accuracy, loss, etc.)
- ✅ **Metadata** (dates, configuration, etc.)

## 📁 File Details

- **Filename**: `extended_model.pth`
- **Size**: ~10-15 MB
- **Format**: PyTorch checkpoint

## 🎯 What's Next

After downloading, you can:
1. Use it in a Python application
2. Convert to TFLite for mobile apps
3. Deploy to a web service
4. Share with others

⏱️ **Time:** ~30 seconds

▶️ **Run the cell below:**
"""

# ============================================================================
# STEP 6: SAVE AND DOWNLOAD YOUR MODEL
# ============================================================================

"""
What's happening here?
----------------------
We're saving the trained model and downloading it to your computer.

The save() method:
  1. Packages the model weights
  2. Includes original class information
  3. Includes new class information
  4. Adds training metadata
  5. Saves as a .pth file (PyTorch format)

File structure:
  {
    'model_state_dict': [neural network weights],
    'original_classes': [8 class names],
    'new_classes': [your class name],
    'base_model': 'ranasinghehashini/srilankan-food-recognition',
    'training_history': [loss, accuracy per epoch],
    'timestamp': [when trained]
  }

You can load this later with:
  checkpoint = torch.load('extended_model.pth')
  model.load_state_dict(checkpoint['model_state_dict'])
"""

print("="*70)
print("💾 SAVING YOUR EXTENDED MODEL")
print("="*70)

print("\n📝 Saving model checkpoint...")
print("   This includes:")
print("   ✅ Trained model weights")
print("   ✅ All 9 class labels")
print("   ✅ Training history")
print("   ✅ Metadata\n")

# Save the model
model_path = extender.save("extended_model.pth")

# Get file size
import os
file_size_mb = os.path.getsize(model_path) / (1024 * 1024)

print("="*70)
print("✅ MODEL SAVED SUCCESSFULLY!")
print("="*70)

print(f"\n📦 File details:")
print(f"   - Filename: extended_model.pth")
print(f"   - Size: {file_size_mb:.2f} MB")
print(f"   - Location: {model_path}")

print("\n🎯 Model capabilities:")
print("   - Recognizes: 9 food classes")
print("   - Accuracy: {:.1f}%".format(results['best_val_acc']))
print(f"   - Original classes: Preserved ✅")
print(f"   - New class: {class_name} ✅")

print("\n📥 Downloading to your computer...")
print("   (Check your Downloads folder)\n")

# Download the model
from google.colab import files
files.download(model_path)

print("\n" + "="*70)
print("🎊 DOWNLOAD COMPLETE!")
print("="*70)

print("\n📁 Your model file is now in your Downloads folder!")
print("\n🚀 What's next?")
print("   1. Convert to TFLite for mobile deployment")
print("   2. Use in Python applications")
print("   3. Deploy to web services")
print("   4. Share with your team")

print("\n💡 Keep this file safe - it represents hours of training!")

"""---

# 🎊 Congratulations! You Did It!

You've successfully extended the Sri Lankan Food Recognition model with your own food class!

## 📚 What You Learned

✅ How transfer learning works  
✅ How to use the `srilankan-food-trainer` library  
✅ How to prepare and upload training data  
✅ How to train a deep learning model  
✅ How to evaluate model performance  
✅ How to save and download models  

## 🎯 Your Achievement

```
Before:  Model recognized 8 classes
After:   Model recognizes 9 classes (8 original + yours!)
```

The original 8 classes still work perfectly! 🎉

## 🚀 Next Steps

### Option 1: Add More Classes
Want to add another food class? Just run Steps 3-6 again with new images!

### Option 2: Deploy to Mobile
Convert your model to TFLite and use in a Flutter/Android app.

### Option 3: Build a Web App
Create a Flask/FastAPI backend and React frontend.

### Option 4: Share Your Work
Upload your model to Hugging Face and share with the community!

## 📖 Resources

- **GitHub**: [github.com/ranasinghehashini/srilankan-food-recognition](https://github.com/ranasinghehashini/srilankan-food-recognition)
- **Hugging Face**: [huggingface.co/ranasinghehashini/srilankan-food-recognition](https://huggingface.co/ranasinghehashini/srilankan-food-recognition)
- **Documentation**: Check the GitHub README for detailed docs

## 💬 Questions or Issues?

- Open an issue on GitHub
- Check the documentation
- Reach out to the community

## 🌟 Support the Project

If you found this useful:
- ⭐ Star the GitHub repository
- 📢 Share with others
- 🐛 Report bugs or suggest improvements

---

**Thank you for using Sri Lankan Food Trainer!** 🍽️

Happy training! 🎉

---

# 🔧 Troubleshooting Guide

Having issues? Check these common problems and solutions:

## ❌ "Not enough images" error

**Problem**: You uploaded fewer than 20 images.

**Solution**:
- Add more images (minimum 20, recommended 30-50)
- Make sure all images are in JPG/PNG format
- Check that images are not corrupted

## ❌ "Model download failed" error

**Problem**: Cannot download pre-trained model from Hugging Face.

**Solution**:
- Check your internet connection
- Try running the cell again
- If problem persists, restart the Colab runtime

## ❌ "Out of memory" error

**Problem**: Not enough RAM/GPU memory.

**Solution**:
- Restart the Colab runtime (Runtime → Restart runtime)
- Use fewer images (maximum 100 per class)
- Try running at a different time (GPU availability varies)

## ❌ Low accuracy (<80%)

**Problem**: Model is not learning well.

**Solution**:
- Add more high-quality images
- Train for more epochs (try 75 or 100)
- Check image quality (clear, well-lit, focused)
- Make sure all images are of the SAME food type

## ❌ "NotADirectoryError"

**Problem**: ZIP file structure is incorrect.

**Solution**:
Your ZIP should have this structure:
```
potato_tempered.zip
└── potato_tempered/        ← Folder inside ZIP
    ├── img1.jpg
    ├── img2.jpg
    └── ...
```

NOT this:
```
potato_tempered.zip
├── img1.jpg              ← Images directly in ZIP (wrong!)
├── img2.jpg
└── ...
```

## 💡 Still Having Issues?

1. Read the error message carefully
2. Check the GitHub issues page
3. Open a new issue with:
   - Error message
   - What you were trying to do
   - Screenshots if helpful

---

# 📊 Understanding Your Results

## What Do the Numbers Mean?

### Validation Accuracy

This tells you how often the model correctly identifies food in images it hasn't seen during training.

- **90%+**: Excellent! Model is very reliable.
- **85-90%**: Very good! Suitable for most applications.
- **80-85%**: Good! Might need improvement for critical use.
- **<80%**: Needs work. Consider more data or training.

### Loss

Measures how "wrong" the model's predictions are.

- **Lower is better**
- Should decrease over time
- If loss stops decreasing, model has finished learning

### Training Time

Depends on:
- GPU availability (GPU = faster)
- Number of images
- Number of epochs
- Image resolution

## What Makes a Good Training Run?

✅ **Good Signs**:
- Loss decreases steadily
- Validation accuracy increases
- Training completes without errors
- Final accuracy above 85%

⚠️ **Warning Signs**:
- Loss increases or stays flat
- Validation accuracy doesn't improve
- Huge gap between train and validation accuracy (overfitting)

## How to Improve Results

### 1. More Data
- Add more images (up to 100 per class)
- Ensure variety in angles, lighting, backgrounds

### 2. Better Data Quality
- Use high-resolution images
- Ensure good lighting
- Remove blurry/unclear images
- Make sure food is centered

### 3. More Training
- Increase epochs (try 75 or 100)
- Let the model see more examples

### 4. Data Augmentation
- The library automatically does this!
- Rotations, flips, color changes
- Helps model learn better
"""