# -*- coding: utf-8 -*-
"""V1-SriLankanFoodRecognition.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nxU5Nm6tVn6LvB0g1wjue5TZG1JEdZXq
"""

# Cell 1: Mount Google Drive
from google.colab import drive
drive.mount('/content/drive')

"""# Mount Google Drive and Extract Dataset"""

# Cell 2: Extract dataset
import zipfile
import os

# Path to your uploaded zip file
zip_path = '/content/drive/MyDrive/Research-2026/SriLankanFoodRecognition/dataset.zip'

# Extract to Colab
with zipfile.ZipFile(zip_path, 'r') as zip_ref:
    zip_ref.extractall('/content/')

# List what we got
print("Extracted files:")
!ls -la /content/

# Cell 3: Check dataset structure
import os

dataset_path = '/content/dataset'


# List all classes
classes = [d for d in os.listdir(dataset_path)
           if os.path.isdir(os.path.join(dataset_path, d))
           and not d.startswith('.')]

print(f"Found {len(classes)} classes:\n")

# Count images per class
for class_name in sorted(classes):
    class_path = os.path.join(dataset_path, class_name)
    images = [f for f in os.listdir(class_path)
              if f.lower().endswith(('.png', '.jpg', '.jpeg'))]
    print(f"  {class_name:30s} : {len(images):3d} images")

print(f"\nTotal classes: {len(classes)}")

"""# Visualize Some Images"""

# Cell 4: Visualize sample images
import matplotlib.pyplot as plt
from PIL import Image
import random

fig, axes = plt.subplots(2, 4, figsize=(16, 8))
axes = axes.flatten()

for idx, class_name in enumerate(sorted(classes)[:8]):
    class_path = os.path.join(dataset_path, class_name)
    images = [f for f in os.listdir(class_path)
              if f.lower().endswith(('.png', '.jpg', '.jpeg'))]

    # Pick random image
    random_img = random.choice(images)
    img_path = os.path.join(class_path, random_img)

    # Display
    img = Image.open(img_path)
    axes[idx].imshow(img)
    axes[idx].set_title(class_name, fontsize=10)
    axes[idx].axis('off')

plt.tight_layout()
plt.show()

"""# Install Required Packages"""

# Cell 5: Install packages
!pip install -q torch torchvision
!pip install -q scikit-learn
!pip install -q tqdm

print("✅ All packages installed!")

"""# Split Dataset into Train/Val/Test"""

# Cell 6: Split dataset
import shutil
from pathlib import Path
import random

# Configuration
DATASET_DIR = '/content/dataset'
OUTPUT_DIR = '/content/dataset_split'
TRAIN_RATIO = 0.7
VAL_RATIO = 0.15
TEST_RATIO = 0.15

# Create output directories
for split in ['train', 'val', 'test']:
    os.makedirs(os.path.join(OUTPUT_DIR, split), exist_ok=True)

# Get all class folders
class_folders = [f for f in os.listdir(DATASET_DIR)
                 if os.path.isdir(os.path.join(DATASET_DIR, f))
                 and not f.startswith('.')]

print(f"Splitting {len(class_folders)} classes into train/val/test...\n")

# Process each class
for class_name in sorted(class_folders):
    class_path = os.path.join(DATASET_DIR, class_name)

    # Get all images in this class
    images = [f for f in os.listdir(class_path)
              if f.lower().endswith(('.png', '.jpg', '.jpeg'))]

    # Shuffle
    random.seed(42)  # For reproducibility
    random.shuffle(images)

    # Calculate split sizes
    total = len(images)
    train_size = int(total * TRAIN_RATIO)
    val_size = int(total * VAL_RATIO)

    train_images = images[:train_size]
    val_images = images[train_size:train_size + val_size]
    test_images = images[train_size + val_size:]

    print(f"{class_name:30s} → Train: {len(train_images):2d} | Val: {len(val_images):2d} | Test: {len(test_images):2d}")

    # Copy files to respective splits
    for split, img_list in [('train', train_images),
                            ('val', val_images),
                            ('test', test_images)]:
        split_class_dir = os.path.join(OUTPUT_DIR, split, class_name)
        os.makedirs(split_class_dir, exist_ok=True)

        for img in img_list:
            src = os.path.join(class_path, img)
            dst = os.path.join(split_class_dir, img)
            shutil.copy2(src, dst)

print("\n✅ Dataset split complete!")
print(f"Output saved to: {OUTPUT_DIR}")

"""# Create the Model Architecture"""

# Cell 7: Define the model
import torch
import torch.nn as nn
import torch.nn.functional as F

class EmbeddingNet(nn.Module):
    """
    Custom embedding network for few-shot food recognition
    Outputs 128-dimensional embeddings
    """
    def __init__(self, embedding_dim=128):
        super(EmbeddingNet, self).__init__()

        # Convolutional layers
        self.conv1 = nn.Conv2d(3, 32, kernel_size=3, padding=1)
        self.bn1 = nn.BatchNorm2d(32)
        self.pool1 = nn.MaxPool2d(2, 2)

        self.conv2 = nn.Conv2d(32, 64, kernel_size=3, padding=1)
        self.bn2 = nn.BatchNorm2d(64)
        self.pool2 = nn.MaxPool2d(2, 2)

        self.conv3 = nn.Conv2d(64, 128, kernel_size=3, padding=1)
        self.bn3 = nn.BatchNorm2d(128)
        self.pool3 = nn.MaxPool2d(2, 2)

        self.conv4 = nn.Conv2d(128, 256, kernel_size=3, padding=1)
        self.bn4 = nn.BatchNorm2d(256)
        self.pool4 = nn.MaxPool2d(2, 2)

        # Global Average Pooling
        self.gap = nn.AdaptiveAvgPool2d(1)

        # Fully connected layers
        self.fc1 = nn.Linear(256, 256)
        self.dropout = nn.Dropout(0.3)
        self.fc2 = nn.Linear(256, embedding_dim)

    def forward(self, x):
        # Conv blocks
        x = self.pool1(F.relu(self.bn1(self.conv1(x))))
        x = self.pool2(F.relu(self.bn2(self.conv2(x))))
        x = self.pool3(F.relu(self.bn3(self.conv3(x))))
        x = self.pool4(F.relu(self.bn4(self.conv4(x))))

        # Global Average Pooling
        x = self.gap(x)
        x = x.view(x.size(0), -1)

        # Embedding layers
        x = F.relu(self.fc1(x))
        x = self.dropout(x)
        embedding = self.fc2(x)

        # L2 normalize
        embedding = F.normalize(embedding, p=2, dim=1)

        return embedding


class PrototypicalNetwork(nn.Module):
    """Complete prototypical network"""
    def __init__(self, embedding_dim=128):
        super(PrototypicalNetwork, self).__init__()
        self.embedding_net = EmbeddingNet(embedding_dim)

    def forward(self, x):
        return self.embedding_net(x)

# Test the model
model = PrototypicalNetwork(embedding_dim=128)
dummy_input = torch.randn(1, 3, 224, 224)
output = model(dummy_input)

print("✅ Model created successfully!")
print(f"Input shape: {dummy_input.shape}")
print(f"Output shape: {output.shape}")
print(f"Output (embedding): {output[0][:5]}...")  # Show first 5 values

"""# Create Dataset Loader and Helper Functions"""

# Cell 8: Dataset and helper functions
from torch.utils.data import Dataset
from torchvision import transforms
from PIL import Image
import random

class FoodDataset(Dataset):
    """Dataset for Sri Lankan food images"""
    def __init__(self, root_dir, transform=None):
        self.root_dir = root_dir
        self.transform = transform

        # Get all classes
        self.classes = sorted([d for d in os.listdir(root_dir)
                               if os.path.isdir(os.path.join(root_dir, d))
                               and not d.startswith('.')])

        self.class_to_idx = {cls: idx for idx, cls in enumerate(self.classes)}

        # Get all image paths
        self.samples = []
        for class_name in self.classes:
            class_dir = os.path.join(root_dir, class_name)
            class_idx = self.class_to_idx[class_name]

            for img_name in os.listdir(class_dir):
                if img_name.lower().endswith(('.png', '.jpg', '.jpeg')):
                    img_path = os.path.join(class_dir, img_name)
                    self.samples.append((img_path, class_idx))

        print(f"✅ Loaded {len(self.samples)} images from {len(self.classes)} classes")

    def __len__(self):
        return len(self.samples)

    def __getitem__(self, idx):
        img_path, label = self.samples[idx]
        image = Image.open(img_path).convert('RGB')

        if self.transform:
            image = self.transform(image)

        return image, label


def create_episode(dataset, n_way, k_shot, q_query):
    """
    Create a single training episode for few-shot learning

    Args:
        dataset: FoodDataset
        n_way: Number of classes per episode
        k_shot: Number of support examples per class
        q_query: Number of query examples per class

    Returns:
        support_images, support_labels, query_images, query_labels
    """
    # Randomly select n_way classes
    all_classes = list(range(len(dataset.classes)))
    selected_classes = random.sample(all_classes, n_way)

    # Organize samples by class
    class_samples = {cls: [] for cls in selected_classes}
    for img_path, label in dataset.samples:
        if label in selected_classes:
            class_samples[label].append(img_path)

    support_images = []
    support_labels = []
    query_images = []
    query_labels = []

    for cls_idx, cls in enumerate(selected_classes):
        # Sample k_shot + q_query images
        samples = random.sample(class_samples[cls], k_shot + q_query)

        # Split into support and query
        support_paths = samples[:k_shot]
        query_paths = samples[k_shot:]

        # Load images
        for path in support_paths:
            img = Image.open(path).convert('RGB')
            support_images.append(img)
            support_labels.append(cls_idx)

        for path in query_paths:
            img = Image.open(path).convert('RGB')
            query_images.append(img)
            query_labels.append(cls_idx)

    return support_images, support_labels, query_images, query_labels


def compute_prototypes(embeddings, labels):
    """
    Compute class prototypes as mean of embeddings

    Args:
        embeddings: (N, embedding_dim)
        labels: (N,)

    Returns:
        prototypes: (num_classes, embedding_dim)
        class_labels: (num_classes,)
    """
    unique_labels = torch.unique(labels)
    prototypes = []

    for label in unique_labels:
        class_embeddings = embeddings[labels == label]
        prototype = class_embeddings.mean(dim=0)
        prototypes.append(prototype)

    prototypes = torch.stack(prototypes)
    return prototypes, unique_labels


def prototypical_loss(query_embeddings, prototypes, query_labels, prototype_labels):
    """
    Compute prototypical loss

    Args:
        query_embeddings: (M, embedding_dim)
        prototypes: (num_classes, embedding_dim)
        query_labels: (M,)
        prototype_labels: (num_classes,)

    Returns:
        loss: scalar
    """
    # Compute distances (negative distances = logits)
    distances = torch.cdist(query_embeddings, prototypes)
    logits = -distances

    # Find the index of correct prototype for each query
    targets = torch.zeros_like(query_labels)
    for i, label in enumerate(query_labels):
        targets[i] = (prototype_labels == label).nonzero(as_tuple=True)[0]

    # Cross-entropy loss
    loss = F.cross_entropy(logits, targets)
    return loss

print("✅ Helper functions defined!")

"""# Load Datasets"""

# Cell 9: Load datasets
DATASET_DIR = '/content/dataset_split'

# Data augmentation for training
train_transform = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.RandomHorizontalFlip(),
    transforms.RandomRotation(15),
    transforms.ColorJitter(brightness=0.2, contrast=0.2, saturation=0.1),
    transforms.ToTensor(),
    transforms.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225])
])

# No augmentation for validation
val_transform = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.ToTensor(),
    transforms.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225])
])

# Load datasets (without transform for now - we'll apply in episodes)
train_dataset = FoodDataset(os.path.join(DATASET_DIR, 'train'), transform=None)
val_dataset = FoodDataset(os.path.join(DATASET_DIR, 'val'), transform=None)
test_dataset = FoodDataset(os.path.join(DATASET_DIR, 'test'), transform=None)

print("\n📊 Dataset Statistics:")
print(f"Training:   {len(train_dataset.samples)} images")
print(f"Validation: {len(val_dataset.samples)} images")
print(f"Testing:    {len(test_dataset.samples)} images")
print(f"\nClasses: {train_dataset.classes}")

"""# Setup Training Configuration"""

# Cell 10: Training configuration
import torch.optim as optim

# Device configuration
DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"🖥️  Using device: {DEVICE}")

if torch.cuda.is_available():
    print(f"   GPU: {torch.cuda.get_device_name(0)}")
    print(f"   Memory: {torch.cuda.get_device_properties(0).total_memory / 1e9:.2f} GB")

# Hyperparameters
EMBEDDING_DIM = 128
LEARNING_RATE = 0.0001
NUM_EPOCHS = 150  # Reduced for faster testing
N_WAY = 4
K_SHOT = 2
Q_QUERY = 2

EPISODES_PER_EPOCH = 100

# Initialize model
model = PrototypicalNetwork(embedding_dim=EMBEDDING_DIM).to(DEVICE)
optimizer = optim.Adam(model.parameters(), lr=LEARNING_RATE)
scheduler = optim.lr_scheduler.StepLR(optimizer, step_size=50, gamma=0.5)

print(f"\n⚙️  Training Configuration:")
print(f"   Embedding Dimension: {EMBEDDING_DIM}")
print(f"   Learning Rate: {LEARNING_RATE}")
print(f"   Epochs: {NUM_EPOCHS}")
print(f"   Episodes per Epoch: {EPISODES_PER_EPOCH}")
print(f"   Few-shot setup: {N_WAY}-way {K_SHOT}-shot")
print(f"\n✅ Model and optimizer ready!")

"""# Create Training and Validation Functions"""

# Cell 11: Training and validation functions
from tqdm import tqdm

def train_one_epoch(model, dataset, transform, device, n_way, k_shot, q_query, episodes):
    """Train for one epoch"""
    model.train()
    epoch_losses = []
    correct = 0
    total = 0

    pbar = tqdm(range(episodes), desc="Training")
    for _ in pbar:
        # Create episode
        support_imgs, support_lbls, query_imgs, query_lbls = create_episode(
            dataset, n_way, k_shot, q_query
        )

        # Transform images to tensors
        support_tensors = torch.stack([transform(img) for img in support_imgs]).to(device)
        query_tensors = torch.stack([transform(img) for img in query_imgs]).to(device)
        support_labels = torch.tensor(support_lbls).to(device)
        query_labels = torch.tensor(query_lbls).to(device)

        # Forward pass
        support_embeddings = model(support_tensors)
        query_embeddings = model(query_tensors)

        # Compute prototypes
        prototypes, prototype_labels = compute_prototypes(support_embeddings, support_labels)

        # Compute loss
        loss = prototypical_loss(query_embeddings, prototypes, query_labels, prototype_labels)

        # Backward pass
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

        # Calculate accuracy for this episode
        distances = torch.cdist(query_embeddings, prototypes)
        predictions = distances.argmin(dim=1)
        pred_labels = prototype_labels[predictions]
        correct += (pred_labels == query_labels).sum().item()
        total += len(query_labels)

        epoch_losses.append(loss.item())
        pbar.set_postfix({
            'loss': f'{loss.item():.4f}',
            'acc': f'{100.0 * correct / total:.1f}%'
        })

    avg_loss = sum(epoch_losses) / len(epoch_losses)
    accuracy = 100.0 * correct / total
    return avg_loss, accuracy


def validate(model, dataset, transform, device, n_way, k_shot, q_query, episodes=50):
    """Validate the model"""
    model.eval()
    correct = 0
    total = 0

    with torch.no_grad():
        for _ in tqdm(range(episodes), desc="Validating"):
            # Create episode
            support_imgs, support_lbls, query_imgs, query_lbls = create_episode(
                dataset, n_way, k_shot, q_query
            )

            # Transform images
            support_tensors = torch.stack([transform(img) for img in support_imgs]).to(device)
            query_tensors = torch.stack([transform(img) for img in query_imgs]).to(device)
            support_labels = torch.tensor(support_lbls).to(device)
            query_labels = torch.tensor(query_lbls).to(device)

            # Forward pass
            support_embeddings = model(support_tensors)
            query_embeddings = model(query_tensors)

            # Compute prototypes
            prototypes, prototype_labels = compute_prototypes(support_embeddings, support_labels)

            # Predictions
            distances = torch.cdist(query_embeddings, prototypes)
            predictions = distances.argmin(dim=1)
            pred_labels = prototype_labels[predictions]

            correct += (pred_labels == query_labels).sum().item()
            total += len(query_labels)

    accuracy = 100.0 * correct / total
    return accuracy

print("✅ Training functions ready!")

"""# START TRAINING"""

# Cell: Quick verification
import os

SAVE_DIR = '/content/drive/MyDrive/Research-2026/SriLankanFoodRecognition'

# Check if Drive is mounted
if os.path.exists('/content/drive/MyDrive'):
    print("✅ Google Drive is mounted")
else:
    print("❌ Google Drive NOT mounted - run drive.mount() first!")

# Create directory
os.makedirs(SAVE_DIR, exist_ok=True)

# Verify it exists
if os.path.exists(SAVE_DIR):
    print(f"✅ Directory ready: {SAVE_DIR}")
else:
    print(f"❌ Failed to create directory")

# Test write permission
test_file = f'{SAVE_DIR}/test.txt'
try:
    with open(test_file, 'w') as f:
        f.write('test')
    os.remove(test_file)
    print("✅ Write permission confirmed")
except:
    print("❌ Cannot write to this location")

# Cell: Training with Google Drive Auto-Save (Your Custom Path)
import time
from datetime import datetime
import torch
import os

# ✅ YOUR GOOGLE DRIVE PATH
SAVE_DIR = '/content/drive/MyDrive/Research-2026/SriLankanFoodRecognition'
SAVE_PATH = f'{SAVE_DIR}/best_model.pth'

# Ensure directory exists
os.makedirs(SAVE_DIR, exist_ok=True)

print(f"✅ Save directory created/verified: {SAVE_DIR}")

# Track history
train_losses = []
train_accs = []
val_accs = []
best_val_acc = 0.0

print("="*70)
print("🚀 STARTING TRAINING")
print("="*70)
print(f"Start time: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
print(f"Device: {DEVICE}")
print(f"Classes: {train_dataset.classes}")
print(f"💾 Model will be saved to: {SAVE_PATH}")
print("="*70 + "\n")

start_time = time.time()

for epoch in range(NUM_EPOCHS):
    epoch_start = time.time()

    print(f"\n📍 Epoch {epoch+1}/{NUM_EPOCHS}")
    print("-" * 70)

    # Train
    train_loss, train_acc = train_one_epoch(
        model, train_dataset, train_transform, DEVICE,
        N_WAY, K_SHOT, Q_QUERY, EPISODES_PER_EPOCH
    )

    # Validate
    val_acc = validate(
        model, val_dataset, val_transform, DEVICE,
        N_WAY, K_SHOT, Q_QUERY, episodes=50
    )

    # Learning rate scheduling
    scheduler.step()
    current_lr = optimizer.param_groups[0]['lr']

    # Save history
    train_losses.append(train_loss)
    train_accs.append(train_acc)
    val_accs.append(val_acc)

    # Print epoch summary
    epoch_time = time.time() - epoch_start
    print(f"\n📊 Epoch {epoch+1} Summary:")
    print(f"   Train Loss: {train_loss:.4f}")
    print(f"   Train Acc:  {train_acc:.2f}%")
    print(f"   Val Acc:    {val_acc:.2f}%")
    print(f"   LR:         {current_lr:.6f}")
    print(f"   Time:       {epoch_time:.1f}s")

    # ✅ SAVE BEST MODEL TO YOUR GOOGLE DRIVE PATH
    if val_acc > best_val_acc:
        best_val_acc = val_acc
        torch.save({
            'epoch': epoch,
            'model_state_dict': model.state_dict(),
            'optimizer_state_dict': optimizer.state_dict(),
            'val_acc': val_acc,
            'classes': train_dataset.classes,
            'train_losses': train_losses,
            'train_accs': train_accs,
            'val_accs': val_accs,
        }, SAVE_PATH)
        print(f"   ✅ NEW BEST MODEL SAVED TO GOOGLE DRIVE!")
        print(f"   📂 {SAVE_PATH}")
        print(f"   🎯 Val Acc: {val_acc:.2f}%")

    print("-" * 70)

    # ✅ CHECKPOINT EVERY 10 EPOCHS
    if (epoch + 1) % 10 == 0:
        checkpoint_path = f'{SAVE_DIR}/checkpoint_epoch_{epoch+1}.pth'
        torch.save({
            'epoch': epoch,
            'model_state_dict': model.state_dict(),
            'optimizer_state_dict': optimizer.state_dict(),
            'val_acc': val_acc,
            'classes': train_dataset.classes,
            'train_losses': train_losses,
            'train_accs': train_accs,
            'val_accs': val_accs,
            'best_val_acc': best_val_acc,
        }, checkpoint_path)
        print(f"   💾 Checkpoint: checkpoint_epoch_{epoch+1}.pth")

total_time = time.time() - start_time

print("\n" + "="*70)
print("🎉 TRAINING COMPLETE!")
print("="*70)
print(f"Total time: {total_time/60:.1f} minutes")
print(f"Best Validation Accuracy: {best_val_acc:.2f}%")
print(f"Final Training Accuracy: {train_accs[-1]:.2f}%")
print(f"\n💾 All files saved to:")
print(f"📂 {SAVE_DIR}/")
print("="*70)

"""# Stop Training & Load Best Model"""

# Cell 1: Load Best Model
import torch
import numpy as np
from PIL import Image
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import confusion_matrix, classification_report
from tqdm import tqdm
import json
import os
import shutil

print("="*70)
print("📊 LOADING BEST MODEL FOR EVALUATION")
print("="*70)

# Load best model
SAVE_DIR = '/content/drive/MyDrive/Research-2026/SriLankanFoodRecognition'
checkpoint = torch.load(f'{SAVE_DIR}/best_model.pth')

# Restore model
model.load_state_dict(checkpoint['model_state_dict'])
model.eval()

print(f"✅ Best Model Loaded!")
print(f"   Epoch: {checkpoint['epoch']+1}")
print(f"   Validation Accuracy: {checkpoint['val_acc']:.2f}%")
print(f"   Classes: {checkpoint['classes']}")
print("="*70)

from PIL import Image, UnidentifiedImageError

SAFE_IMAGE_PATH = '/content/dataset_split/test/pumpkin_red_curry/pumpkin_red_curry_001.jpg'

test_correct = 0
test_total = 0
num_episodes = 200

print(f"Running {num_episodes} test episodes...")

with torch.no_grad():
    for _ in tqdm(range(num_episodes)):
        try:
            # Create episode
            support_imgs, support_lbls, query_imgs, query_lbls = create_episode(
                test_dataset, N_WAY, K_SHOT, Q_QUERY
            )

            # Replace corrupted support images
            for i, img in enumerate(support_imgs):
                try:
                    img.verify()
                except Exception:
                    print(f"⚠️ Replacing corrupted support image with safe image")
                    support_imgs[i] = Image.open(SAFE_IMAGE_PATH).convert('RGB')

            # Replace corrupted query images
            for i, img in enumerate(query_imgs):
                try:
                    img.verify()
                except Exception:
                    print(f"⚠️ Replacing corrupted query image with safe image")
                    query_imgs[i] = Image.open(SAFE_IMAGE_PATH).convert('RGB')

            # Transform
            support_tensors = torch.stack([val_transform(img) for img in support_imgs]).to(DEVICE)
            query_tensors = torch.stack([val_transform(img) for img in query_imgs]).to(DEVICE)
            support_labels = torch.tensor(support_lbls).to(DEVICE)
            query_labels = torch.tensor(query_lbls).to(DEVICE)

            # Embeddings
            support_embeddings = model(support_tensors)
            query_embeddings = model(query_tensors)

            # Prototypes
            prototypes, prototype_labels = compute_prototypes(support_embeddings, support_labels)

            # Predictions
            distances = torch.cdist(query_embeddings, prototypes)
            predictions = distances.argmin(dim=1)
            pred_labels = prototype_labels[predictions]

            test_correct += (pred_labels == query_labels).sum().item()
            test_total += len(query_labels)

        except (UnidentifiedImageError, OSError) as e:
            print(f"❌ Skipping episode due to unexpected error: {e}")
            continue

test_accuracy = 100.0 * test_correct / test_total
print(f"\n✅ FEW-SHOT TEST ACCURACY: {test_accuracy:.2f}%")
print(f"   Correct: {test_correct}/{test_total}")

"""# Full Test Set Evaluation + Confusion Matrix"""

# Cell 3: Full Test Set Evaluation
print("\n" + "="*70)
print("📊 FULL TEST SET EVALUATION")
print("="*70)

classes = checkpoint['classes']

# Compute class prototypes from training data
print("Computing class prototypes from training set...")
class_prototypes = {}

with torch.no_grad():
    for class_idx, class_name in enumerate(classes):
        class_samples = [s for s in train_dataset.samples if s[1] == class_idx]

        embeddings = []
        for img_path, _ in class_samples:
            img = Image.open(img_path).convert('RGB')
            img_tensor = val_transform(img).unsqueeze(0).to(DEVICE)
            embedding = model(img_tensor)
            embeddings.append(embedding)

        prototype = torch.cat(embeddings).mean(dim=0)
        class_prototypes[class_idx] = prototype
        print(f"  ✅ {class_name:30s}: {len(embeddings):3d} images")

# Test on all test images
print("\n📊 Testing on all test images...")
predictions = []
true_labels = []
confidences = []

with torch.no_grad():
    for img_path, label in tqdm(test_dataset.samples, desc="Evaluating"):
        img = Image.open(img_path).convert('RGB')
        img_tensor = val_transform(img).unsqueeze(0).to(DEVICE)
        embedding = model(img_tensor)

        # Find closest prototype
        distances = {idx: torch.dist(embedding, proto.unsqueeze(0)).item()
                    for idx, proto in class_prototypes.items()}
        pred = min(distances, key=distances.get)
        conf = 1.0 / (1.0 + distances[pred])

        predictions.append(pred)
        true_labels.append(label)
        confidences.append(conf)

predictions = np.array(predictions)
true_labels = np.array(true_labels)
full_accuracy = 100.0 * (predictions == true_labels).sum() / len(true_labels)

print(f"\n✅ FULL TEST ACCURACY: {full_accuracy:.2f}%")
print(f"   Total images: {len(true_labels)}")
print(f"   Correct: {(predictions == true_labels).sum()}")
print(f"   Average confidence: {np.mean(confidences):.2%}")

# Save full test results
full_results = {
    'full_test_accuracy': float(full_accuracy),
    'total_images': len(true_labels),
    'correct': int((predictions == true_labels).sum()),
    'average_confidence': float(np.mean(confidences))
}

with open(f'{SAVE_DIR}/full_test_results.json', 'w') as f:
    json.dump(full_results, f, indent=2)

print(f"✅ Saved: full_test_results.json")

"""# Confusion Matrix"""

# Cell 4: Confusion Matrix
print("\n" + "="*70)
print("📈 CREATING CONFUSION MATRIX")
print("="*70)

cm = confusion_matrix(true_labels, predictions)

plt.figure(figsize=(10, 8))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
            xticklabels=classes, yticklabels=classes,
            cbar_kws={'label': 'Count'})
plt.title('Confusion Matrix - Sri Lankan Food Recognition\n90% Validation Accuracy',
          fontsize=14, fontweight='bold', pad=20)
plt.ylabel('True Label', fontsize=12)
plt.xlabel('Predicted Label', fontsize=12)
plt.xticks(rotation=45, ha='right')
plt.yticks(rotation=0)
plt.tight_layout()
plt.savefig(f'{SAVE_DIR}/confusion_matrix.png', dpi=300, bbox_inches='tight')
plt.show()

print("✅ Saved: confusion_matrix.png")

# Classification Report
print("\n" + "="*70)
print("CLASSIFICATION REPORT")
print("="*70)
report = classification_report(true_labels, predictions,
                              target_names=classes, digits=3)
print(report)

with open(f'{SAVE_DIR}/classification_report.txt', 'w') as f:
    f.write("Sri Lankan Food Recognition - Classification Report\n")
    f.write("Best Model: Epoch 40, Val Acc: 90.00%\n")
    f.write("="*70 + "\n\n")
    f.write(report)

print("✅ Saved: classification_report.txt")

"""# Per-Class Accuracy"""

# Cell 5: Per-Class Accuracy
print("\n" + "="*70)
print("📊 PER-CLASS ACCURACY ANALYSIS")
print("="*70)

per_class_acc = []
per_class_counts = []

for class_idx, class_name in enumerate(classes):
    mask = true_labels == class_idx
    if mask.sum() > 0:
        acc = (predictions[mask] == true_labels[mask]).mean() * 100
        count = mask.sum()
    else:
        acc = 0
        count = 0

    per_class_acc.append(acc)
    per_class_counts.append(count)
    print(f"{class_name:30s}: {acc:6.2f}% ({count:2d} images)")

# Plot
plt.figure(figsize=(12, 6))
colors = ['green' if a >= 85 else 'orange' if a >= 70 else 'red'
          for a in per_class_acc]
bars = plt.bar(range(len(classes)), per_class_acc, color=colors,
               edgecolor='black', linewidth=1.5)

# Add count labels
for i, (bar, count) in enumerate(zip(bars, per_class_counts)):
    height = bar.get_height()
    plt.text(bar.get_x() + bar.get_width()/2., height + 1,
             f'n={count}', ha='center', va='bottom', fontsize=9)

plt.xlabel('Food Class', fontsize=12)
plt.ylabel('Accuracy (%)', fontsize=12)
plt.title('Per-Class Recognition Accuracy\nBest Model: 90% Validation Accuracy',
          fontsize=14, fontweight='bold')
plt.xticks(range(len(classes)), classes, rotation=45, ha='right')
plt.axhline(y=np.mean(per_class_acc), color='blue', linestyle='--',
            linewidth=2, label=f'Mean: {np.mean(per_class_acc):.1f}%')
plt.legend(fontsize=10)
plt.ylim(0, 105)
plt.grid(axis='y', alpha=0.3)
plt.tight_layout()
plt.savefig(f'{SAVE_DIR}/per_class_accuracy.png', dpi=300, bbox_inches='tight')
plt.show()

print("\n✅ Saved: per_class_accuracy.png")

# Save metrics
per_class_metrics = {
    class_name: {
        'accuracy': float(acc),
        'num_samples': int(count)
    }
    for class_name, acc, count in zip(classes, per_class_acc, per_class_counts)
}

with open(f'{SAVE_DIR}/per_class_metrics.json', 'w') as f:
    json.dump(per_class_metrics, f, indent=2)

print("✅ Saved: per_class_metrics.json")

"""# Training Curves (From History)"""

# Cell 6: Training Curves
print("\n" + "="*70)
print("📈 CREATING TRAINING CURVES")
print("="*70)

# Extract history from checkpoint
train_losses = checkpoint['train_losses']
train_accs = checkpoint['train_accs']
val_accs = checkpoint['val_accs']

fig, axes = plt.subplots(1, 3, figsize=(18, 5))

# Loss
axes[0].plot(train_losses, linewidth=2, color='blue')
axes[0].set_title('Training Loss', fontsize=14, fontweight='bold')
axes[0].set_xlabel('Epoch', fontsize=12)
axes[0].set_ylabel('Loss', fontsize=12)
axes[0].grid(True, alpha=0.3)
axes[0].axvline(x=40, color='red', linestyle='--', alpha=0.5, label='Best Model (Epoch 40)')
axes[0].legend()

# Accuracy
axes[1].plot(train_accs, label='Training', linewidth=2, color='green')
axes[1].plot(val_accs, label='Validation', linewidth=2, color='orange')
axes[1].axhline(y=90, color='red', linestyle='--', linewidth=2, label='Best: 90.00%')
axes[1].axvline(x=40, color='red', linestyle='--', alpha=0.5)
axes[1].set_title('Accuracy Over Time', fontsize=14, fontweight='bold')
axes[1].set_xlabel('Epoch', fontsize=12)
axes[1].set_ylabel('Accuracy (%)', fontsize=12)
axes[1].legend(fontsize=10)
axes[1].grid(True, alpha=0.3)

# Learning Rate
epochs = list(range(1, len(train_losses) + 1))
lrs = [0.0001 if e <= 50 else 0.00005 for e in epochs]
axes[2].plot(lrs, linewidth=2, color='purple')
axes[2].axvline(x=40, color='red', linestyle='--', alpha=0.5, label='Best Model')
axes[2].set_title('Learning Rate Schedule', fontsize=14, fontweight='bold')
axes[2].set_xlabel('Epoch', fontsize=12)
axes[2].set_ylabel('Learning Rate', fontsize=12)
axes[2].set_yscale('log')
axes[2].legend()
axes[2].grid(True, alpha=0.3)

plt.tight_layout()
plt.savefig(f'{SAVE_DIR}/training_curves.png', dpi=300, bbox_inches='tight')
plt.show()

print("✅ Saved: training_curves.png")

"""# Sample Predictions (Correct & Incorrect)"""

# Cell 7: Sample Predictions
print("\n" + "="*70)
print("📸 SAMPLE PREDICTIONS")
print("="*70)

correct_indices = np.where(predictions == true_labels)[0]
incorrect_indices = np.where(predictions != true_labels)[0]

print(f"Correct predictions: {len(correct_indices)}")
print(f"Incorrect predictions: {len(incorrect_indices)}")

# Show 8 correct predictions
if len(correct_indices) >= 8:
    fig, axes = plt.subplots(2, 4, figsize=(16, 8))
    axes = axes.flatten()

    sample_correct = np.random.choice(correct_indices, 8, replace=False)

    for idx, ax in zip(sample_correct, axes):
        img_path, true_label = test_dataset.samples[idx]
        conf = confidences[idx]

        img = Image.open(img_path)
        ax.imshow(img)
        ax.set_title(f'✓ {classes[true_label]}\nConfidence: {conf:.1%}',
                    color='green', fontsize=10, fontweight='bold')
        ax.axis('off')

    plt.suptitle('Correct Predictions (Sample)', fontsize=16, fontweight='bold', y=1.02)
    plt.tight_layout()
    plt.savefig(f'{SAVE_DIR}/correct_predictions.png', dpi=300, bbox_inches='tight')
    plt.show()
    print("✅ Saved: correct_predictions.png")

# Show incorrect predictions (if any)
if len(incorrect_indices) > 0:
    num_show = min(8, len(incorrect_indices))
    fig, axes = plt.subplots(2, 4, figsize=(16, 8))
    axes = axes.flatten()

    sample_incorrect = np.random.choice(incorrect_indices, num_show, replace=False)

    for i, (idx, ax) in enumerate(zip(sample_incorrect, axes)):
        if i >= num_show:
            ax.axis('off')
            continue

        img_path, true_label = test_dataset.samples[idx]
        pred_label = predictions[idx]
        conf = confidences[idx]

        img = Image.open(img_path)
        ax.imshow(img)
        ax.set_title(f'True: {classes[true_label]}\nPred: {classes[pred_label]}\n{conf:.1%}',
                    color='red', fontsize=9, fontweight='bold')
        ax.axis('off')

    for i in range(num_show, 8):
        axes[i].axis('off')

    plt.suptitle('Incorrect Predictions', fontsize=16, fontweight='bold', y=1.02)
    plt.tight_layout()
    plt.savefig(f'{SAVE_DIR}/incorrect_predictions.png', dpi=300, bbox_inches='tight')
    plt.show()
    print("✅ Saved: incorrect_predictions.png")
else:
    print("🎉 NO INCORRECT PREDICTIONS! Perfect test set performance!")

"""# Export Model for Deployment"""

# Cell 8: Export Model
print("\n" + "="*70)
print("📦 EXPORTING MODEL FOR DEPLOYMENT")
print("="*70)

export_dir = f'{SAVE_DIR}/exported_model'
os.makedirs(export_dir, exist_ok=True)

# 1. Copy PyTorch model
shutil.copy(f'{SAVE_DIR}/best_model.pth', f'{export_dir}/best_model.pth')
print("✅ PyTorch model (.pth)")

# 2. TorchScript for mobile
model.eval()
dummy = torch.randn(1, 3, 224, 224).to(DEVICE)
traced = torch.jit.trace(model, dummy)
traced.save(f'{export_dir}/model_torchscript.pt')
print("✅ TorchScript model (.pt)")

# 3. Model info JSON
model_info = {
    'model_name': 'Sri Lankan Food Recognition',
    'architecture': 'Custom Prototypical Network',
    'embedding_dim': 128,
    'input_size': [224, 224],
    'classes': classes,
    'num_classes': len(classes),
    'normalization': {
        'mean': [0.485, 0.456, 0.406],
        'std': [0.229, 0.224, 0.225]
    },
    'performance': {
        'best_epoch': 40,
        'validation_accuracy': 90.00,
        'test_accuracy': float(test_accuracy),
        'full_test_accuracy': float(full_accuracy),
        'mean_per_class_accuracy': float(np.mean(per_class_acc))
    },
    'training': {
        'total_epochs_trained': len(train_losses),
        'n_way': 5,
        'k_shot': 5,
        'learning_rate': 0.0001,
        'dataset_size': {
            'train': len(train_dataset.samples),
            'val': len(val_dataset.samples),
            'test': len(test_dataset.samples)
        }
    }
}

with open(f'{export_dir}/model_info.json', 'w') as f:
    json.dump(model_info, f, indent=2)

print("✅ Model info (JSON)")

# 4. Usage guide
usage = f"""# Sri Lankan Food Recognition Model

## Model Information
- **Architecture**: Custom Prototypical Network
- **Embedding Dimension**: 128
- **Input Size**: 224×224 RGB images
- **Classes**: {len(classes)}
- **Best Validation Accuracy**: 90.00%
- **Test Accuracy**: {test_accuracy:.2f}%

## Classes
{chr(10).join([f'{i+1}. {cls}' for i, cls in enumerate(classes)])}

## Python Usage
```python
import torch
from torchvision import transforms
from PIL import Image

# Load model
checkpoint = torch.load('best_model.pth')
model = PrototypicalNetwork(embedding_dim=128)
model.load_state_dict(checkpoint['model_state_dict'])
model.eval()

# Prepare transform
transform = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.ToTensor(),
    transforms.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225])
])

# Load and predict
img = Image.open('food.jpg').convert('RGB')
img_tensor = transform(img).unsqueeze(0)

with torch.no_grad():
    embedding = model(img_tensor)
    # Compare with prototypes for classification
```

## Mobile Usage
Use `model_torchscript.pt` with PyTorch Mobile for Flutter/React Native.

## Citation
If you use this model, please cite:
[Your Name], "A Transformation-Aware Deep Learning Approach for Recognizing Cooked Vegetable Ingredients in Sri Lankan Cuisine", 2026.

## Model Performance

| Metric | Value |
|--------|-------|
| Validation Accuracy | 90.00% |
| Test Accuracy (Few-shot) | {test_accuracy:.2f}% |
| Full Test Accuracy | {full_accuracy:.2f}% |
| Mean Per-Class Accuracy | {np.mean(per_class_acc):.2f}% |
"""

with open(f'{export_dir}/README.md', 'w') as f:
    f.write(usage)

print("✅ Usage guide (README.md)")

print(f"\n📁 All files exported to: {export_dir}/")
print("="*70)

"""# Final Summary Report"""

# Cell 9: Final Summary
print("\n" + "="*80)
print("🎉 EVALUATION COMPLETE - FINAL SUMMARY")
print("="*80)

summary = f"""
MODEL INFORMATION:
  Architecture: Custom Prototypical Network
  Embedding Dimension: 128
  Training Method: Few-shot episodic learning (5-way 5-shot)
  Best Epoch: 40
  Total Epochs Trained: {len(train_losses)}

DATASET:
  Training Images: {len(train_dataset.samples)}
  Validation Images: {len(val_dataset.samples)}
  Test Images: {len(test_dataset.samples)}
  Total Images: {len(train_dataset.samples) + len(val_dataset.samples) + len(test_dataset.samples)}
  Classes: {len(classes)}

PERFORMANCE METRICS:
  ✅ Best Validation Accuracy: 90.00%
  ✅ Few-Shot Test Accuracy: {test_accuracy:.2f}%
  ✅ Full Test Accuracy: {full_accuracy:.2f}%
  ✅ Mean Per-Class Accuracy: {np.mean(per_class_acc):.2f}%
  ✅ Average Confidence: {np.mean(confidences):.1%}

BEST PERFORMING CLASSES:
"""

top_3 = np.argsort(per_class_acc)[-3:][::-1]
for idx in top_3:
    summary += f"  {classes[idx]:30s}: {per_class_acc[idx]:.2f}%\n"

summary += "\nWORST PERFORMING CLASSES:\n"
worst_3 = np.argsort(per_class_acc)[:3]
for idx in worst_3:
    summary += f"  {classes[idx]:30s}: {per_class_acc[idx]:.2f}%\n"

# Add generated files section
summary += f"""
FILES GENERATED:
  ✅ best_model.pth - Trained model weights
  ✅ model_torchscript.pt - Mobile-ready model
  ✅ model_info.json - Complete model metadata
  ✅ training_curves.png - Training visualization
  ✅ confusion_matrix.png - Confusion matrix
  ✅ per_class_accuracy.png - Per-class performance
  ✅ correct_predictions.png - Sample correct predictions
  ✅ incorrect_predictions.png - Sample errors (if any)
  ✅ test_results.json - Test metrics
  ✅ full_test_results.json - Full test metrics
  ✅ per_class_metrics.json - Per-class breakdown
  ✅ classification_report.txt - Detailed report
  ✅ README.md - Usage documentation

ALL FILES SAVED TO:
  📂 {SAVE_DIR}/
"""  # <-- THIS CLOSING TRIPLE QUOTE WAS MISSING

# Print summary
print(summary)

# Save summary
with open(f'{SAVE_DIR}/EVALUATION_SUMMARY.txt', 'w') as f:
    f.write(summary)

print("✅ Summary saved to: EVALUATION_SUMMARY.txt")